name: Test

on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'main'
  #   paths:
  #     - 'aws-cloud/ec2/*'
  # pull_request:
  #   branches:
  #     - 'main'

jobs:
  test-variable:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest stable version of actions/checkout
      
      - name: Run command
        run: |
          echo "Accessing repository variable: ${{ vars.MY_COMMAND }}"  >> command
          ls -la
          cat command
